### ISSUE TITLE
USER STORY: Matching label size with parcel size

### ISSUE THREAD

**Issue by emilyrosenberg** [emilyrosenberg/agile-project#2]
As a **warehouse operator** I can **select paper size on which to print** so that **the printed label matches the parcel size**

### Acceptance criteria
- Order details must include the order id, the shipping address and the list of items in the parcel
- The warehouse employee is able to select the size of the order details from 3 sizes (A4, A5 and A6)
- The font size used is 12 point.

### Tasks
- [ ] Design a “print” icon and add  it to the order details page. 
- [ ] Design the print layouts  for the different page sizes.
- [ ] Create the HTML and CSS for the  dropdown menu including the paper sizes. 
- [ ] Create the code for the  model, viewer and controller. 
- [ ] Test the completed functionality.

**Comment by emilyrosenberg** [comment]
This is completed
